apiVersion: v1
kind: Secret
metadata:
  name: {{ include "craftbeer.fullname" . }}
  labels:
{{ include "craftbeer.labels" . | indent 4 }}
type: Opaque
data:
  password: {{ .Values.properties.database.password | b64enc }}